### ISSUE TITLE
[ci] Travis no longer giving credits for OSS

### ISSUE THREAD

**Issue by seik** [kotlin-telegram-bot/kotlin-telegram-bot#131]
Title. Travis is no longer giving free runtime for OSS. We should migrate to another service and I was thinking in Github Actions.

I'm open to hear any other option.

**Comment by vjgarciag96** [comment]
Oh... 😢

Github Actions sounds good to me 👍🏻. But I'm also open to hear about other options offering free infrastructure for open source repos if someone else wants to propose an alternative (I'll also investigate a bit more about the different options and its pros and cons when I have some time).

**Comment by red-avtovo** [comment]
Github Actions also sounds good to me. What about CircleCi as an alternative?

**Comment by vjgarciag96** [comment]
I made a quick migration to Github Actions to not block PRs due to this.

The set up was really straightforward, it's running properly (we've the same we had before with Travis) and it's integrated with Gihub, so in the *Actions* tab you can check the workflows we've run (https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/actions?query=branch%3Amaster).

I also created a sample PR making a test fail (https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/135) and it's also quite the same we had.

I wouldn't invest much more time on this right now given that our CI requirements are really simple and are now totally covered by Github Actions.

**Comment by seik** [comment]
Seems good to me @vjgarciag96 @red-avtovo !

Closing this and the test PR.
